### ISSUE TITLE
Autoscan suggested value is invalid

### ISSUE THREAD

**Issue by slozanolulo** [ryanphillipthomas/veracode-security#1]
Hi, looks like the default values on the auto_scan options are invalid, those are predefined as "yes" and "no" but the accepted values are true or false

**Comment by ryanphillipthomas** [comment]
Thanks for your note, I'll take a look at those.

**Comment by siddarthgandhi** [comment]
@ryanphillipthomas is there an update on this?

**Comment by ryanphillipthomas** [comment]
Sorry for the delay, https://github.com/bitrise-io/bitrise-steplib/pull/3050 once this is merged in this should be resolved.
